name: "sabios"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v21
      with:
        skip_adding_nixpkgs_channel: true
    - run: |
        export NIXPKGS_ALLOW_UNFREE=1
        echo '[]' > keys.nix
        nix-shell --run 'home-manager build -v -A sabios'
